export function registerSetupPage(app, config, apiKeyGuard) {
  const pageGuard = config.dashboard?.protectPage ? apiKeyGuard(config) : (_req, _res, next) => next();
  app.get('/setup', pageGuard, (_req, res) => res.type('html').send(renderSetupHtml(config)));
}

function renderSetupHtml(config) {
  const needsKey = Boolean(config.server.requireApiKey);
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hermes Setup Center</title><style>${css()}</style></head><body><main><h1>Hermes Setup Center</h1><p>Set provider/API key untuk Hermes-only router. Hermes cukup diarahkan ke local endpoint router.</p><section class="card"><label>Router API Key</label><input id="localKey" type="password" placeholder="${needsKey ? 'Paste server.apiKey / hrk_xxx' : 'API key guard off'}"><button onclick="saveLocalKey()">Save Local Key</button><button onclick="loadConfig()">Load Config</button><a href="/dashboard">Open Dashboard</a></section><section class="grid"><article><h2>Hermes App Settings</h2><p>Masukkan ini di Hermes:</p><pre id="hermesBox">Load config dulu...</pre></article><article><h2>Provider Presets</h2><div id="presets">Load config dulu...</div></article></section><section class="card"><h2>Provider / LLM API</h2><label>Provider Base URL</label><input id="baseUrl" placeholder="https://openrouter.ai/api"><label>Provider API Key</label><input id="providerKey" type="password" placeholder="sk-or-xxx / provider key"><label>Chat Path</label><input id="chatPath" value="/v1/chat/completions"><label>Models Path</label><input id="modelsPath" value="/v1/models"><label>Timeout ms</label><input id="timeoutMs" value="120000"><div class="row"><button onclick="saveProvider()">Save Provider</button><button onclick="testProvider()">Test Provider</button></div><pre id="result">Ready.</pre></section></main><script>${js()}</script></body></html>`;
}

function css() {
  return `:root{color-scheme:dark;--bg:#080b12;--panel:#101827;--border:#223047;--text:#e8eefc;--muted:#91a0b8;--accent:#7c3aed;--accent2:#06b6d4;--good:#36d399;--bad:#fb7185}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:radial-gradient(circle at top left,rgba(124,58,237,.22),transparent 35%),var(--bg);color:var(--text)}main{max-width:1120px;margin:0 auto;padding:36px 18px}h1{font-size:34px;margin:0 0 6px}p{color:var(--muted)}.card,article{background:rgba(16,24,39,.78);border:1px solid var(--border);border-radius:20px;padding:18px;margin:16px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.grid article{margin:0}label{display:block;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em;margin-top:12px}input{width:100%;background:#070a11;color:var(--text);border:1px solid var(--border);border-radius:12px;padding:12px;margin-top:6px}button,a{display:inline-block;background:linear-gradient(135deg,var(--accent),var(--accent2));color:white;border:0;border-radius:12px;padding:11px 14px;margin:12px 8px 0 0;font-weight:700;text-decoration:none;cursor:pointer}.row{display:flex;flex-wrap:wrap;gap:8px}pre{background:#070a11;border:1px solid var(--border);border-radius:12px;padding:12px;overflow:auto;color:#cbd5e1}.preset{display:block;width:100%;text-align:left;background:#172033;border:1px solid var(--border)}@media(max-width:860px){.grid{grid-template-columns:1fr}}`;
}

function js() {
  return `const lk=document.getElementById('localKey');lk.value=localStorage.getItem('hermesRouterApiKey')||'';function hdr(){const k=localStorage.getItem('hermesRouterApiKey')||'';return {'content-type':'application/json',...(k?{Authorization:'Bearer '+k}:{})}}function saveLocalKey(){localStorage.setItem('hermesRouterApiKey',lk.value.trim());loadConfig()}async function loadConfig(){try{const r=await fetch('/dashboard/api/config',{headers:hdr()});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();fill(d);out('Loaded config.')}catch(e){out('Load failed: '+e.message)}}function fill(d){hermesBox.textContent=JSON.stringify({baseUrl:d.hermes.baseUrl,apiKey:d.hermes.apiKeyPreview},null,2);baseUrl.value=d.config.hermes.baseUrl||'';chatPath.value=d.config.hermes.chatPath||'/v1/chat/completions';modelsPath.value=d.config.hermes.modelsPath||'/v1/models';timeoutMs.value=d.config.hermes.timeoutMs||120000;presets.innerHTML=d.presets.map(p=>'<button class="preset" onclick="applyPreset(\''+p.id+'\')">'+p.name+' — '+p.baseUrl+'</button>').join('')}async function applyPreset(id){const r=await fetch('/dashboard/api/provider/preset',{method:'POST',headers:hdr(),body:JSON.stringify({id})});out(await r.text());loadConfig()}async function saveProvider(){const payload={hermes:{baseUrl:baseUrl.value,apiKey:providerKey.value,chatPath:chatPath.value,modelsPath:modelsPath.value,timeoutMs:Number(timeoutMs.value)}};const r=await fetch('/dashboard/api/config',{method:'POST',headers:hdr(),body:JSON.stringify(payload)});out(await r.text());loadConfig()}async function testProvider(){const r=await fetch('/dashboard/api/provider/test',{method:'POST',headers:hdr(),body:'{}'});out(await r.text())}function out(t){result.textContent=t}loadConfig();`;
}
